return {
    Animation = require("telegram.structures.Animation"),
    Audio = require("telegram.structures.Audio"),
    Chat = require("telegram.structures.Chat"),
    Contact = require("telegram.structures.Contact"),
    Dice = require("telegram.structures.Dice"),
    Document = require("telegram.structures.Document"),
    Game = require("telegram.structures.Game"),
    InlineKeyboardMarkup = require("telegram.structures.InlineKeyboardMarkup"),
    Location = require("telegram.structures.Location"),
    Message = require("telegram.structures.Message"),
    MessageEntity = require("telegram.structures.MessageEntity"),
    PhotoSize = require("telegram.structures.PhotoSize"),
    PollOption = require("telegram.structures.PollOption"),
    Update = require("telegram.structures.Update"),
    User = require("telegram.structures.User"),
    Venue = require("telegram.structures.Venue"),
    Video = require("telegram.structures.Video"),
    VideoNote = require("telegram.structures.VideoNote"),
    Voice = require("telegram.structures.Voice"),
}